### PR TITLE
chore: Cleaned up GitHub Action Workflows

### LINKED ISSUE #19: Cleanup GitHub Actions workflows
**Context**

1. We want to make sure we have healthy community and people respec each other in GitHub. We want to monitor all comments in every repository and analyze sentiments to identify negative ones and get proper notification. Idea is to use GitHub Actions for it, to check sentiments with Google Natural Language API and post negative comments to Slack for review.

2. We manage community files in global `.github` repo, and we have GitHub Funding config file there too. As a result we need to cleanup all the repos to remove `.github/FUNDING.yml`

3. Start supporting new GitHub [pull request event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) that allows gives access to `GITHUB_TOKEN` with write access. Fix welcome contributors workflow is needed.

4. We want to automatically merge Pull Requests that are submitted by [Dependanbot](https://dependabot.com/). New workflow needs to be added, or if already existins it needs to be modified

**Description**

1. Add this workflow file called `sentiment-analysis.yml` to `.github/workflows` (create it if it doesn't exist yet) directory: https://gist.github.com/derberg/ab362e4b37f542e7e1813e67b7cb11ee
    Proper secrets are already added to GitHub organization so it is as simple as adding above file to workflows dir.
2. Remove `.github/FUNDING.yml` if it exists
3. If not done already rename `pull_request` from line 4 to `pull_request_target` in `.github/workflows/welcome-first-time-contrib.yml` file
4. Create new file called `automerge.yml` with the following content: https://gist.github.com/derberg/024814a26959d54f683e7bd68d68f007
    If the repository already has a file called `automerge-release-pr-bump.yml` than rename it and adjust `if` statements to check `github.actor == 'asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'` instead of `github.actor == 'asyncapi-bot'`

### PR DESCRIPTION
**Pull request by C-Zekeri**
**Description**

- Added `sentiment-analysis.yml` workflow file
- Removed `.github/FUNDING.yml`
- Edited line 4 in `.github/workflows/welcome-first-time-contrib.yml` file
- Adjusted if statement in `automerge.yml` file.

**Related issue(s)**
Fixes #19 

If there is anything you need me to change or adjust, please let me know. Thank you!

### CODE REVIEW

**Review by derberg — APPROVED** [review]
@C-Zekeri all perfect. I just made conventional commit prefix lowercase, that is all

I have to say that I envy you for discipline to make these 4 changes each in a separate commit. This is a best practice I always forget to follow 😢 but it is so much helpful for a reviewer! Thanks you 🙇

**Comment by C-Zekeri** [comment]
Thank you very much for making this a very encouraging environment @derberg!

**Comment by derberg** [comment]
@C-Zekeri thanks, these kind words mean it was worth it 🙇

**Comment by derberg** [comment]
@C-Zekeri sorry but I forgot that what you changed [here](https://github.com/asyncapi/asyncapi-node/blob/master/.github/workflows/automerge.yml#L29) should also be done [here](https://github.com/asyncapi/asyncapi-node/blob/master/.github/workflows/automerge.yml#L39). Would you mind opening another PR?

**Comment by C-Zekeri** [comment]
Not at all. I'll get to it as soon as I can, thank you.

**Pull request merged**
