### PR TITLE
fix: change minItems of oneOf and anyOf to 1

### PR DESCRIPTION
**Pull request by Z5eyhS0uubejR0SVmX2O**
**Description**
Replica of https://github.com/asyncapi/asyncapi/pull/493

**Related issue(s)**
Resolves https://github.com/asyncapi/asyncapi/issues/492

### CODE REVIEW

**Comment by derberg** [comment]
@Z5eyhS0uubejR0SVmX2O this is strange that it did not pop up before but just now 🤔 (I mean issue with PR testing because of the missing `lint` script)

Can you please add [such a script](https://github.com/asyncapi/asyncapi/blob/master/package.json#L10) to the package.json file 🙏🏼

**Review by derberg — APPROVED** [review]
🙇🏼 
once you add the lint script I approve again (as the new commit will dismiss my approval)

**Comment by Z5eyhS0uubejR0SVmX2O** [comment]
@derberg Updated as indicated.

**Comment by derberg** [comment]
oh man, I truly hate windows

**Review by derberg — APPROVED** [review]

**Pull request merged**
