### PR TITLE
fix: add messageId property to message definition

### PR DESCRIPTION
**Pull request by WaleedAshraf**
issue https://github.com/asyncapi/asyncapi/issues/458

### CODE REVIEW

**Review by derberg — APPROVED** [review]

**Review by fmvilas — CHANGES_REQUESTED** [review]
I don't think it should be added here yet. The messageId field is not part of the 2.0.0 spec. It will probably be landing on 2.1.0 or 3.0.0. We should close this PR.

**Comment by WaleedAshraf** [comment]
As @derberg said earlier, there is no clear versioning / semver for Schema itself. We have been fixing stuff in 2.0.0, without version bump.

**Comment by fmvilas** [comment]
We have been merging fixes to the schema, which is understandable. This introduces a new feature and that's totally different.

**Comment by WaleedAshraf** [comment]
Ok. Is there some roadmap/plan for 2.1.0? Are there any other new features on hold?

**Comment by fmvilas** [comment]
There are no plans yet. In the upcoming weeks, we'll be announcing a few things that should allow us to move faster :)

Regarding things on hold: https://github.com/asyncapi/asyncapi/compare/2.0.0...master. There's at least the Mercure binding waiting.

**Comment by derberg** [comment]
And also we have this issue from @lbroudoux to improve message examples.
We had those grouped under https://github.com/asyncapi/asyncapi/issues/353 (you need to have zenhub installed to see related linked issues to this epic) but that will need review as it is few months old

**Comment by WaleedAshraf** [comment]
Ok. I'll be waiting for announcements ;)
You guys would be working on a lot of things but having a roadmap would help both sides. (users and core contributors)
I'll try to hop-on on the next weekly meeting to have some more details about this.

**Comment by fmvilas** [comment]
We do [have a roadmap](https://app.zenhub.com/workspaces/asyncapi-initiative-5e541969da30b0bc34628b22/roadmap) (and you're part of the organization on Zehub) but it's impossible for us to follow. That's why I decided not to create a new one yet. It would be utter bullshit from our side to plan things for a whole year when things are moving so fast. We'll follow a different approach soon, just give us time to reorganize :)

**Comment by WaleedAshraf** [comment]
@fmvilas I see it. Yup, that is what I was looking for. 👍 
I understand (and see) there's a bunch of stuff ongoing. Hopefully from next year, things will be in better shape.

**Comment by derberg** [comment]
@WaleedAshraf I suggest we close it and when you are ready to work on it you will open it up properly from a fork and point to a release branch. Agreed?

**Pull request closed without merging**
